global_costmap:
  global_frame: odom # 一边走一边来可以直接使用odom
  robot_base_frame: base_link #
  # 以此实现坐标变换

  update_frequency: 10.0 #代价地图更新频率
  publish_frequency: 10.0 #代价地图的发布频率
  transform_tolerance: 0.5 #等待坐标变换发布信息的超时时间

  static_map: false # 是否使用一个地图或者地图服务器来初始化全局代价地图，如果不使用静态地图，这个参数为false.
  rolling_window: true # 启用滚动窗口（以机器人为中心动态更新）
  width: 20.0
  height: 20.0
  resolution: 0.05

  #膨胀半径，扩展在碰撞区域以外的代价区域，使得机器人规划路径避开障碍物
  inflation_radius: 0.5
  #代价比例系数，越大则代价值越小
  cost_scaling_factor: 10.0
