use_sim_time: false
# target_frame: base_link
min_height: -0.5
max_height: 6.0
min_intensity: 0.1
max_intensity: 2.0
angle_min: -3.1415926
angle_max: 3.1415926
angle_increment: 0.00872665
scan_time: 0.05
range_min: 0.3
range_max: 10.0
use_inf: true
concurrency_level: 2